### ISSUE TITLE
Fatal Exception: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.netmera.*']

### ISSUE THREAD

**Issue by Frequencies** [Netmera/netmera-fintech-android#12]
Hello, I observe a lot of problems with such crashes, all of them in background

netmera_core_version = "3.9.10"
netmera_fcm_version = "3.9.3"
netmera_hms_version = "3.9.5"

Could you check and provide fixes for this?

```
Fatal Exception: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.netmera.o1']
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:60)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at org.koin.core.Koin.get(Koin.java:130)
       at com.netmera.NetmeraKoinJavaComponent.get(NetmeraKoinJavaComponent.kt:2)
       at com.netmera.NetmeraKoinJavaComponent.get$default(NetmeraKoinJavaComponent.kt:1)
       at com.netmera.NMInitializer$b.a(NMInitializer.kt:1)
       at com.netmera.NMInitializer$b.invoke(NMInitializer.kt)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.netmera.NMInitializer.create$lambda-0(NMInitializer.kt)
       at com.netmera.NMInitializer.access$create$lambda-0(NMInitializer.kt)
       at com.netmera.NMInitializer$a.invokeSuspend(NMInitializer.kt:2)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7876)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

```
Caused by org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.netmera.l0']
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:60)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at com.netmera.NetmeraKoin$a$a.a(NetmeraKoin.kt:47)
       at com.netmera.NetmeraKoin$a$a.invoke(NetmeraKoin.kt:1)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at org.koin.core.Koin.get(Koin.java:130)
       at com.netmera.NetmeraKoinJavaComponent.get(NetmeraKoinJavaComponent.kt:2)
       at com.netmera.NetmeraKoinJavaComponent.get$default(NetmeraKoinJavaComponent.kt:1)
       at com.netmera.NMInitializer$b.a(NMInitializer.kt:1)
       at com.netmera.NMInitializer$b.invoke(NMInitializer.kt)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.netmera.NMInitializer.create$lambda-0(NMInitializer.kt)
       at com.netmera.NMInitializer.access$create$lambda-0(NMInitializer.kt)
       at com.netmera.NMInitializer$a.invokeSuspend(NMInitializer.kt:2)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7876)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

```
Caused by org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.netmera.s1']
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:60)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at com.netmera.NetmeraKoin$a$t.a(NetmeraKoin.kt:50)
       at com.netmera.NetmeraKoin$a$t.invoke(NetmeraKoin.kt:1)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at com.netmera.NetmeraKoin$a$a.a(NetmeraKoin.kt:47)
       at com.netmera.NetmeraKoin$a$a.invoke(NetmeraKoin.kt:1)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at org.koin.core.Koin.get(Koin.java:130)
       at com.netmera.NetmeraKoinJavaComponent.get(NetmeraKoinJavaComponent.kt:2)
       at com.netmera.NetmeraKoinJavaComponent.get$default(NetmeraKoinJavaComponent.kt:1)
       at com.netmera.NMInitializer$b.a(NMInitializer.kt:1)
       at com.netmera.NMInitializer$b.invoke(NMInitializer.kt)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.netmera.NMInitializer.create$lambda-0(NMInitializer.kt)
       at com.netmera.NMInitializer.access$create$lambda-0(NMInitializer.kt)
       at com.netmera.NMInitializer$a.invokeSuspend(NMInitializer.kt:2)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7876)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

```
Caused by org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'com.netmera.w0']
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:60)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at com.netmera.NetmeraKoin$a$s.a(NetmeraKoin.kt:51)
       at com.netmera.NetmeraKoin$a$s.invoke(NetmeraKoin.kt:1)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at com.netmera.NetmeraKoin$a$t.a(NetmeraKoin.kt:50)
       at com.netmera.NetmeraKoin$a$t.invoke(NetmeraKoin.kt:1)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at com.netmera.NetmeraKoin$a$a.a(NetmeraKoin.kt:47)
       at com.netmera.NetmeraKoin$a$a.invoke(NetmeraKoin.kt:1)
       at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
       at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
       at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.java:20)
       at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
       at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.java:110)
       at org.koin.core.scope.Scope.resolveValue(Scope.kt:254)
       at org.koin.core.scope.Scope.resolveInstance(Scope.kt:241)
       at org.koin.core.scope.Scope.get(Scope.kt:204)
       at org.koin.core.Koin.get(Koin.java:130)
       at com.netmera.NetmeraKoinJavaComponent.get(NetmeraKoinJavaComponent.kt:2)
       at com.netmera.NetmeraKoinJavaComponent.get$default(NetmeraKoinJavaComponent.kt:1)
       at com.netmera.NMInitializer$b.a(NMInitializer.kt:1)
       at com.netmera.NMInitializer$b.invoke(NMInitializer.kt)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.netmera.NMInitializer.create$lambda-0(NMInitializer.kt)
       at com.netmera.NMInitializer.access$create$lambda-0(NMInitializer.kt)
       at com.netmera.NMInitializer$a.invokeSuspend(NMInitializer.kt:2)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7876)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by bsoykal** [comment]
Hi @Frequencies, No Koin library is integrated with the Netmera version you mentioned. Did you update your app from an old Netmera build? If yes, please try cleaning and rebuilding your project.

**Comment by bsoykal** [comment]
Closed because of inactivity.
